version: '3.1'
services:
 nodejs:
   build:
     context: .
     dockerfile: Dockerfile
     args:
       buildno: 1
   ports:
      - 80:8080
   networks:
      - overlay
   deploy:
      mode: replicated
      replicas: 2
